steps:
  - name: "hashicorp/terraform"
    entrypoint: "sh"
    args:
      - "-c"
      - |
        terraform init &&
        terraform validate &&
        terraform plan -out=tfplan &&
        terraform apply -auto-approve tfplan
